### ISSUE TITLE
A bug about tile preview

### ISSUE THREAD

**Issue by salttttfish** [Naotsun19B/GraphPrinter-Document#1]
Hello! your plugin is very useful, like it.But here's the puzzle.
I don't know if other versions have this problem. In version 4.26, when "Material Graph Export Method：Combine Preview and Graph" is selected, the preview node of the material blueprint can't display the graphic content.

Material Graph Export Method：Combine Preview and Graph
![image](https://user-images.githubusercontent.com/108986228/233928690-5e36f853-6979-463a-9fde-692794751a70.png)

Material Graph Export Method：Graph Only
![image](https://user-images.githubusercontent.com/108986228/233928748-b0f70f29-347d-464e-9956-802c3beccfcb.png)

**Comment by Naotsun19B** [comment]
Thank you for using the plugin.
I am not aware of this defect. I will look into fixing the bug, but since 4.26 is no longer supported in the marketplace, you will need to download it from the Github repository after upgrading.
I apologize for the inconvenience and hope you will wait for the fix.

**Comment by salttttfish** [comment]
Thank you for taking the time to fix it


&nbsp;


十二
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Naotsun19B/GraphPrinter-Document] A bug about tile preview (Issue #1)





 
感谢您使用该插件。
我不知道这个缺陷。我将研究修复该错误，但由于市场上不再支持 4.26，因此您需要在升级后从 Github 存储库下载它。
对于给您带来的不便，我深表歉意，并希望您等待修复。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;
