### ISSUE TITLE
Not working in UE 5.2

### ISSUE THREAD

**Issue by sonuislearning** [Naotsun19B/GraphPrinter-Document#2]
Please update the plugin.

**Comment by Naotsun19B** [comment]
Do you mean that UE5.2 is not available in the marketplace? 
Or do you mean that the latest plugin obtained from Github does not work with UE5.2?

**Comment by sonuislearning** [comment]
Plugin does not work with ue5.2

**Comment by sonuislearning** [comment]
plugin does not work with UE5.2

**Comment by Naotsun19B** [comment]
Is it correct that the latest plugin plugin obtained from Github does not work with UE5.2? 
Do you mean that all the functions available from the shortcut keys, tool menu, and toolbar do not work?

**Comment by sonuislearning** [comment]
yes, it says, modules need to be rebuilt and then compilation fails.

**Comment by Naotsun19B** [comment]
That is probably because the environment is not C++ buildable or the project is Blueprint only. 
[Here](https://github.com/Naotsun19B/GraphPrinter/releases/tag/UE5.2) is a package of plugins for UE5.2 including binaries.

**Comment by sonuislearning** [comment]
Thank you so much.
